import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },

  // Home Screen Styles
  welcomeCard: {
    backgroundColor: "#2E8B57",
    margin: 16,
    padding: 20,
    borderRadius: 12,
  },
  welcomeTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 8,
  },
  welcomeSubtitle: {
    fontSize: 16,
    color: "#fff",
    opacity: 0.9,
  },
  quickActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 16,
    marginBottom: 16,
  },
  actionCard: {
    flex: 1,
    padding: 20,
    borderRadius: 12,
    alignItems: "center",
    marginHorizontal: 4,
  },
  primaryAction: {
    backgroundColor: "#3498db",
  },
  secondaryAction: {
    backgroundColor: "#e74c3c",
  },
  tertiaryAction: {
    backgroundColor: "#f39c12",
  },
  quaternaryAction: {
    backgroundColor: "#9b59b6",
  },
  actionCardText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 8,
    textAlign: "center",
  },
  activeQueueCard: {
    backgroundColor: "#fff",
    margin: 16,
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: "#2E8B57",
  },
  activeQueueTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2E8B57",
    marginBottom: 8,
  },
  activeQueueInfo: {
    fontSize: 16,
    color: "#333",
    marginBottom: 4,
  },
  activeQueueWait: {
    fontSize: 14,
    color: "#666",
  },

  // Clinics Screen Styles
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    margin: 16,
    backgroundColor: "#fff",
    borderRadius: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  searchInput: {
    flex: 1,
    height: 40,
    fontSize: 16,
  },
  searchIcon: {
    marginLeft: 8,
  },

  // Symptoms Screen Styles
  symptomInstructions: {
    backgroundColor: "#fff",
    margin: 16,
    padding: 16,
    borderRadius: 12,
  },
  instructionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 8,
  },
  instructionText: {
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
  },
  symptomsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginHorizontal: 16,
  },
  symptomCard: {
    backgroundColor: "#fff",
    width: "48%",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 2,
    borderColor: "#e0e0e0",
    position: "relative",
  },
  selectedSymptom: {
    borderColor: "#2E8B57",
    backgroundColor: "#e8f5e8",
  },
  symptomIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  symptomName: {
    fontSize: 14,
    fontWeight: "500",
    color: "#333",
    textAlign: "center",
  },
  urgentLabel: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: "#e74c3c",
    color: "#fff",
    fontSize: 8,
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
    fontWeight: "bold",
  },
  symptomDescription: {
    margin: 16,
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 12,
  },
  descriptionLabel: {
    fontSize: 16,
    fontWeight: "500",
    color: "#333",
    marginBottom: 8,
  },
  descriptionInput: {
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 8,
    padding: 12,
    height: 100,
    textAlignVertical: "top",
  },
  checkSymptomsBtn: {
    backgroundColor: "#2E8B57",
    margin: 16,
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  disabledBtn: {
    backgroundColor: "#ccc",
  },
  checkSymptomsBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },

  // Appointments Screen Styles
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
  },
  emptyStateText: {
    fontSize: 16,
    color: "#666",
    marginTop: 16,
    marginBottom: 8,
    textAlign: "center",
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
    marginBottom: 16,
  },
  bookNewBtn: {
    backgroundColor: "#2E8B57",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  bookNewBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  appointmentCard: {
    backgroundColor: "#fff",
    margin: 16,
    marginTop: 0,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  appointmentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  appointmentClinic: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    flex: 1,
  },
  appointmentStatus: {
    fontSize: 12,
    color: "#2E8B57",
    fontWeight: "500",
    textTransform: "uppercase",
    backgroundColor: "#e8f5e8",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  appointmentDate: {
    fontSize: 14,
    color: "#666",
    marginBottom: 4,
  },
  appointmentService: {
    fontSize: 14,
    color: "#666",
    marginBottom: 16,
  },
  appointmentActions: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  rescheduleBtn: {
    backgroundColor: "#f39c12",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    flex: 1,
    marginRight: 8,
  },
  rescheduleText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
  },
  cancelBtn: {
    backgroundColor: "#e74c3c",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    flex: 1,
    marginLeft: 8,
  },
  cancelText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
  },

  // Queue Screen Styles
  queueStatusCard: {
    backgroundColor: "#fff",
    margin: 16,
    padding: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  queueStatusTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#2E8B57",
    marginBottom: 16,
    textAlign: "center",
  },
  personalDetailsSection: {
    backgroundColor: "#f8f9fa",
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
  },
  personalDetailsTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#2E8B57",
    marginBottom: 12,
  },
  personalDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  personalDetailLabel: {
    fontSize: 14,
    color: "#666",
    marginLeft: 8,
    flex: 1,
  },
  personalDetailValue: {
    fontSize: 14,
    color: "#333",
    fontWeight: "600",
    flex: 2,
  },
  queueInfoSection: {
    alignItems: "center",
    marginBottom: 16,
  },
  queueInfoTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#2E8B57",
    marginBottom: 8,
  },
  queueStatusClinic: {
    fontSize: 16,
    color: "#333",
    marginBottom: 8,
  },
  queuePositionContainer: {
    alignItems: "center",
    marginVertical: 8,
  },
  queueStatusPosition: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#2E8B57",
    marginBottom: 8,
  },
  queuePositionLabel: {
    fontSize: 14,
    color: "#666",
    marginTop: 4,
  },
  queueStatusWait: {
    fontSize: 16,
    color: "#f39c12",
    marginBottom: 8,
  },
  queueStatusTime: {
    fontSize: 14,
    color: "#666",
    marginBottom: 24,
  },
  notificationStatus: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#e8f5e8",
    padding: 12,
    borderRadius: 8,
    marginBottom: 20,
  },
  notificationText: {
    fontSize: 14,
    color: "#2E8B57",
    marginLeft: 8,
    flex: 1,
  },
  queueActionButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  updateDetailsBtn: {
    backgroundColor: "#3498db",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  updateDetailsText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
    marginLeft: 4,
  },
  leaveQueueBtn: {
    backgroundColor: "#e74c3c",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  leaveQueueText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
    marginLeft: 4,
  },
});
